version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    ports:
        - 55432:5432
    volumes:
        - ./db/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
  app:
    container_name: app
    build: .
    restart: on-failure
    depends_on:
        - db